### ISSUE TITLE
Change Page Title to something meaningful

### ISSUE THREAD

**Issue by DavidGinzberg** [OpenDataDE/tellmewherei.live#2]
The page title is currently `Esri Leaflet Quickstart` from the template it's based on. A name specific to the project/page would be more appropriate.

**Comment by DavidGinzberg** [comment]
First name that comes to mind: "TellMeWhereI.Live -- An Open Data Delaware Project" -- open to other/better ideas.

**Comment by trescube** [comment]
Good call!

**Comment by trescube** [comment]
Fixed!
